kind: Service
apiVersion: v1
metadata:
  name: spring-boot-admin-webservice
  namespace: devops
  labels:
    app: spring-boot-admin
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: spring-boot-admin