apiVersion: v1
kind: Pod
metadata:
  name: admin
  labels:
    app: spring-boot-admin
    component: admin
spec:
  containers:
    image: spring-boot-admin.0975e72
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - port: 8080
  selector:
    app: spring-boot-admin
    component: admin
