apiVersion: v1
kind: Pod
metadata:
  name: admin
  labels:
    app: spring-boot-admin
    component: admin
spec:
  containers:
    - image: spring-boot-admin.bd01f23
      name: spring-boot-admin
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  ports:
    - port: 8080
  selector:
    app: spring-boot-admin
    component: admin
