name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
       
    steps:
     - name: Checkout code
       uses: actions/checkout@v3
       
     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Declare SHA vars to use on other actions
       id: vars
       shell: bash
       run: |
         echo "GITHUB_SHA: ${GITHUB_SHA}"
         echo "::set-output name=sha_short::${GITHUB_SHA::7}"  

     - name: Build and Push
       uses: docker/build-push-action@v2
       with:
         push: true
         tags: deithwen/dev:spring-boot-admin.${{ steps.vars.outputs.sha_short }}
